---

- name: Basic playbook run locally 
  gather_facts: true 
  hosts: 127.0.0.1
  tasks: 
    - name: Doing a ping
      ping:

    - name: Show info
      debug:
        msg: "Machine name: {{ ansible_hostname }}"
...
