---
- name: Restart services
  gather_facts: true
  hosts: host1
  remote_user: root
  become: yes
  tasks:
    - name: Restart apache2
      service:
        name:  apache2
        state: restart
...
