---

- name: Restart services
  hosts: 127.0.0.1
  gather_facts: false

  tasks:
    - name: Restart MySQL and Apache
      service:
        name: "{{ item }}" 
        state: restarted
      with_items: 
        - mysql
        - apache2
...
