---

- name: Restart services
  hosts: lab-awx.ddns.net
  gather_facts: false

  tasks:
    - name: Apache
      service:
        name: "{{ item }}" 
        state: restarted
      with_items: 
        - apache2
...
