---
- name: Reiniciar Apache2 en un contenedor
  hosts: 10.0.3.1 # Reemplaza con el nombre de tu host o grupo de hosts donde esta el contenedor.
  
tasks:
- name: Reiniciar Apache2
  docker_container:
  name: ubuntu_A # Reemplaza con el nombre de tu contenedor
  restart_policy: always
...

