---

- name: Restart services
  hosts: 172.18.0.5
  gather_facts: false

  tasks:
    - name: Restart MySQL and Apache
      service:
        name: "{{ item }}" 
        state: restarted
      with_items: 
        - ssh
...
