---
- name: Restart services
  gather_facts: false
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  
  tasks:
    - name: Restart apache2
      service:
        name:  apache2
        state: restart
...
