---

- name: Restart services
  hosts: 192.168.10.107
  gather_facts: false

  tasks:
    - name: Apache
      service:
        name: "{{ item }}" 
        state: restarted
      with_items: 
        - apache2
...
