---

- name: Restart services
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Apache
      service:
        name: "{{ item }}" 
        state: restart #restarted
      with_items: 
        - apache2
...
