---

- name: Restart services
  hosts: 127.0.0.1
  gather_facts: false

  tasks:
    - name: Apache
      service:
        name: "{{ item }}" 
        state: restarted
      with_items: 
        - apache
...
