---

- name: Basic playbook run locally 
  gather_facts: true 
  hosts: 172.18.0.6
  tasks: 
    - name: Doing a ping
      ping:

    - name: Show info
      debug:
        msg: "Machine name: {{ ansible_hostname }}"
...
