---
- name: Restart services
  gather_facts: false
  hosts: 172.19.0.6
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  become: yes
  
  tasks:
    - name: Restart apache2
      service:
        name:  apache2
        state: stopped
...
